In [1]:
%matplotlib inline
# Use autoreload so that updating hmm_class.py is immediately reflected in future cell executions in the notebook.
# For details on the autoreload extension, see
# https://ipython.org/ipython-doc/3/config/extensions/autoreload.html
%load_ext autoreload
%autoreload 2

In [35]:
import numpy as np
from gaussian import Gaussian
from hmm_class import HMM
from math import log

In [3]:
signal1 = np.array([[ 1. ,  1.1,  0.9, 1.0, 0.0,  0.2,  0.1,  0.3,  3.4,  3.6,  3.5]])
signal2 = np.array([[0.8, 1.2, 0.4, 0.2, 0.15, 2.8, 3.6]])

In [4]:
data = np.hstack([signal1, signal2])
lengths = [11, 7]

In [5]:
hmm = HMM()
hmm.fit(data,lengths, 3)

[[-1], array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2], dtype=int64), [3], array([0, 0, 1, 1, 1, 2, 2], dtype=int64), [3]]
[[-1], array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2], dtype=int64), [3], array([0, 0, 1, 1, 1, 2, 2], dtype=int64), [3]]
[[-1], array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2], dtype=int64), [3], array([0, 0, 1, 1, 1, 2, 2], dtype=int64), [3]]


In [6]:
transitions = np.array([
    [0.66666667,0.33333333, 0.,0.],
    [0.,0.71428571,0.28571429,0.],
    [0.,0.,0.6,0.4],
    [1.,0.,0.,0.],
])

# Define emission distributions (Gaussians)
dists = [
    Gaussian(mean=np.array([1.0]), cov=np.array([[0.01666667]])),
    Gaussian(mean=np.array([0.19285714]), cov=np.array([[0.01459184]])),
    Gaussian(mean=np.array([3.38]), cov=np.array([[0.0896]]))
]

In [7]:
hmm_model = HMM()
hmm_model.load(trans=transitions, dists=dists)

In [8]:
hmm_model.dists[0].get_mean()

array([1.])

In [9]:
samples, states = hmm_model.sample()
print(samples)
print(states)

[[1.10917774]
 [0.16892174]
 [0.20611344]
 [0.17334878]
 [0.09722116]
 [0.23628668]
 [3.46365092]]
[0 1 1 1 1 1 2]


In [10]:
hmm_model.load(trans=transitions, dists=dists)
signal = np.array([[ 0.9515792,   0.9832767,   1.04633007,  1.01464327,  0.98207072, 1.01116689, 0.31622856,  0.20819263,  3.57707616]])
vals = np.array([0, 0, 0, 0, 0, 0, 1, 1, 2])
hmm_model.score(signal, vals)

3.8216312203728853

In [11]:
hmm_model.forward(signal)

3.8216324120843645

In [12]:
hmm_model.viterbi(signal)

(array([0, 0, 0, 0, 0, 0, 1, 1, 2], dtype=int64), 3.8216312203728853)

In [13]:
signal1 = np.array([[ 1. ,  1.1,  0.9, 1.0, 0.0,  0.2,  0.1,  0.3,  3.4,  3.6,  3.5]])
signal2 = np.array([[0.8, 1.2, 0.4, 0.2, 0.15, 2.8, 3.6]])

In [14]:
data = np.hstack([signal1, signal2])
lengths = [11, 7]

In [15]:
hmm = HMM()
hmm.fit(data,lengths, 3)

[[-1], array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2], dtype=int64), [3], array([0, 0, 1, 1, 1, 2, 2], dtype=int64), [3]]
[[-1], array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2], dtype=int64), [3], array([0, 0, 1, 1, 1, 2, 2], dtype=int64), [3]]
[[-1], array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2], dtype=int64), [3], array([0, 0, 1, 1, 1, 2, 2], dtype=int64), [3]]


In [16]:
hmm.trans

array([[0.66666667, 0.33333333, 0.        , 0.        ],
       [0.        , 0.71428571, 0.28571429, 0.        ],
       [0.        , 0.        , 0.90909091, 0.09090909],
       [1.        , 0.        , 0.        , 0.        ]])

In [17]:
hmm.dists[2].get_cov()

array([[0.0896]])

In [18]:
hmm.load(hmm.trans, hmm.dists)

In [19]:
signal = np.array([[ 0.9515792,   0.9832767,   1.04633007,  1.01464327,  0.98207072, 1.01116689, 0.31622856,  0.20819263,  3.57707616]])
hmm.score(signal, vals)

3.821631896208668

In [20]:
hmm.forward(signal)

3.8216330879168874

In [21]:
hmm.viterbi(signal)

(array([0, 0, 0, 0, 0, 0, 1, 1, 2], dtype=int64), 3.8216318962086677)

In [22]:
0.6*0.3*0.2*0.4

0.0144

In [23]:
0.9*0.29

0.261

In [24]:
0.1*0.78

0.07800000000000001

In [25]:
0.71*(0.62*0.261+0.078*0.38)

0.1359366

In [26]:
0.22*(0.14*0.261+0.078*0.86)

0.0227964

In [27]:
0.29*(0.1359366*0.62+0.227964*0.38)

0.04956303348

In [28]:
0.78*(0.1359366*0.14+0.0227964*0.86)

0.030136101840000002

In [29]:
0.04956303348 + 0.030136101840000002

0.07969913532

In [36]:
log(0.07) * -1.31

3.483630648381939

In [37]:
log(0.13)*-1.89

3.856017365915188

In [38]:
-2.04*log(0.31)

2.389213282266008

In [39]:
log(0.27)*-1.47

1.9247199803761303

In [40]:
log(0.22)*-1.51

2.286332876270961

In [45]:
8**4

4096

In [71]:
start = np.array([0.9, 0.1]).reshape(-1,1)
trans = np.array([[0.62, 0.38], [0.14, 0.86]])
emission = np.array([[0.29, 0.71], [0.78, 0.22]])
sign = np.array([0, 1, 0])
hmm.probs(start, trans, emission, sign)

(array([[0.261     , 0.1226454 , 0.02353668],
        [0.078     , 0.0365772 , 0.06088808]]),
 0.08442475956)

In [74]:
4**5

1024

In [76]:
hmm.hidden_state(5, 4)

1024

In [78]:
hmm.hidden_state(4, 8)

4096

In [79]:
start = np.array([0.98, 0.02]).reshape(-1,1)
trans = np.array([[0.94, 0.06], [0.84, 0.16]])
emission = np.array([[0.92, 0.08], [0.23, 0.77]])
sign = np.array([0, 1, 0])
hmm.probs(start, trans, emission, sign)

(array([[0.9016    , 0.06810944, 0.09152915],
        [0.0046    , 0.04222064, 0.00249363]]),
 0.09402278412800001)

In [90]:
prior = np.array([0.07, 0.13, 0.31, 0.27, 0.22])
logarithmic = np.array([-1.31, -1.89, -2.04, -1.47, -1.51])
hmm.posteriori(prior, logarithmic)

(array([0.09966141, 0.10362906, 0.21269424, 0.32757115, 0.25644414]), 4)

In [98]:
trans = np.array([[0.3, 0.1, 0.6], [0.5, 0.4, 0.1], [0.2, 0.3, 0.5]])
start = 2
seq = np.array([2,0,1,2])
hmm.prediction(trans, seq, start)

0.0010000000000000002

In [99]:
trans = np.array([[0.2, 0.2, 0.6], [0.3, 0.3, 0.4], [0.6, 0.1, 0.3]])
start = 2
seq = np.array([2,0,1,2])
hmm.prediction(trans, seq, start)

0.0144

In [100]:
trans = np.array([[0.2, 0.2, 0.6], [0.3, 0.3, 0.4], [0.6, 0.1, 0.3]])
start = 2
seq = np.array([2,0,1,2])
hmm.prediction(trans, seq, start)

0.0144

In [102]:
prior = np.array([0.07, 0.13, 0.31, 0.27, 0.22])
l = np.array([-1.31, -1.89, -2.04, -1.47, -1.51])
hmm.posteriori(prior, l)

(array([0.09966141, 0.10362906, 0.21269424, 0.32757115, 0.25644414]), 4)

In [107]:
hmm.hidden_state(4,8)

4096

In [108]:
start = np.array([0.9, 0.1]).reshape(-1,1)
trans = np.array([[0.62, 0.38],[0.14, 0.86]])
emission = np.array([[0.29, 0.71],[0.78, 0.22]])
sign = np.array([0,1,0])
hmm.probs(start, trans, emission,sign)

(array([[0.261     , 0.1226454 , 0.02353668],
        [0.078     , 0.0365772 , 0.06088808]]),
 0.08442475956)